// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PreGoAccUserBase9999 struct {
	UserID         int32
	UserAccount    string
	UserPassword   string
	UserSalt       string
	UserLoginTime  pgtype.Timestamp
	UserLogoutTime pgtype.Timestamp
	UserLoginIp    pgtype.Text
	UserCreatedAt  pgtype.Timestamp
	UserUpdatedAt  pgtype.Timestamp
}

type PreGoAccUserInfo9999 struct {
	UserID               int64
	UserAccount          string
	UserNickname         pgtype.Text
	UserAvatar           pgtype.Text
	UserState            int16
	UserMobile           pgtype.Text
	UserGender           pgtype.Int2
	UserBirthday         pgtype.Date
	UserEmail            pgtype.Text
	UserIsAuthentication int16
	CreatedAt            pgtype.Timestamp
	UpdatedAt            pgtype.Timestamp
}

type PreGoAccUserVerify9999 struct {
	VerifyID        int32
	VerifyOtp       string
	VerifyKey       string
	VerifyKeyHash   string
	VerifyType      pgtype.Int4
	IsVerified      pgtype.Int4
	IsDeleted       pgtype.Int4
	VerifyCreatedAt pgtype.Timestamp
	VerifyUpdatedAt pgtype.Timestamp
}
