// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type QuangTestV1Goose struct {
	ID        int64
	Name      string
	Age       int32
	Sex       int32
	CreatedAt pgtype.Timestamp
}

type UserV1Goose struct {
	ID        int64
	Name      string
	Age       int32
	Sex       int32
	CreatedAt pgtype.Timestamp
}
