version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: postgres_container
    environment:
      POSTGRES_USER: "postgres" 
      POSTGRES_PASSWORD: "1234567891@" 
      POSTGRES_DB: "shopdevgov2" 
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  redis:
    image: redis:7.0
    container_name: redis_container
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    restart: always
  app:
    container_name: go_backend_crm_shopdev
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8009:8081"
    restart: always
    depends_on: # postgres and redis start before app
      - postgres
      - redis
volumes:
  postgres_data:
  redis_data: