// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/ntquang/ecommerce/internal/controller"
	"github.com/ntquang/ecommerce/internal/repo"
	"github.com/ntquang/ecommerce/internal/services"
)

// Injectors from user.wire.go:

func InitUserRouterHanlder() (*controller.UserController, error) {
	iUserRepository := repo.NewUserRepository()
	iUserAuthRepository := repo.NewUserAuthRepository()
	iUserservice := services.NewUserService(iUserRepository, iUserAuthRepository)
	userController := controller.NewUserController(iUserservice)
	return userController, nil
}
